---
title: "Exosomas"
author: "David Cáceres"
date: "6/7/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Librerias

```{r}
library(ggplot2)
library(edgeR)
library(DESeq2)
library(pheatmap)
library(dplyr)
library(patchwork)
library(ggsci)
library(cowplot)
library(data.table)
library(tibble)
library(magrittr)
library(factoextra)
library(stringr)
library(base)
library(Rfast)
library(swamp)
```



### Directorios de trabajo
```{r}
setwd("~/Exosomas/Exosomas2")
```

### Lectura de los datos
```{r}

count<-read.table(file="RCadj_fullHsa.tsv", header = TRUE, sep = "\t")
quality<-read.table(file="valueHsa.tsv", header = TRUE, sep = "\t")

count<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/RCadj_full_exo1.tsv", header = TRUE, sep = "\t")
quality<-read.table(file="value_exo1.tsv", header = TRUE, sep = "\t")

metadata<-read.table(file="Metadatos.tsv", header = TRUE, sep = "\t")

metadata<-read.table(file="Metadatos.tsv", header = TRUE, sep = "\t")

tipos_exo<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/readsPerc.tsv", header = TRUE, sep = "\t")

brainq<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/brain_q.tsv", header = TRUE, sep = "\t")

short<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/shortReadsPerc.tsv", header = TRUE, sep = "\t")

ushort<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/ultrashort.tsv", header = TRUE, sep = "\t")

ref.genome<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/ref.genome.tsv", header = TRUE, sep = "\t")

unmapped<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/unmapped.tsv", header = TRUE, sep = "\t")

bacteria<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/bacteria.tsv", header = TRUE, sep = "\t")

virus<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/Tablas/virus.tsv", header = TRUE, sep = "\t")
```

### Formato
```{r}
rownames(count) <- count[,1]
count_exo<-count[-1]

rownames(quality) <- quality[,1]
quality_exo<-quality[-1]

metadata_exo<-metadata[-1]

rownames(quality_exo)<-c("s32","s28","s21","s19","s24","s2","s4","s25","s34","s7", "s16","s8","brn","s26","s12", "s27", "s35", "s17", "s29", "s23", "s10","s3", "s15","s1", "s9", "s13", "s18", "s33", "s5", "s31", "s6", "s20","s11", "s22", "s14", "s30")

colnames(count_exo)<-c("s32","s28","s21","s19","s24","s2","s4","s25","s34","s7", "s16","s8","brn","s26","s12", "s27", "s35", "s17", "s29", "s23", "s10","s3", "s15","s1", "s9", "s13", "s18", "s33", "s5", "s31", "s6", "s20","s11", "s22", "s14", "s30")

rownames(metadata)<-c("s32","s28","s21","s19","s24","s2","s4","s25","s34","s7", "s16","s8","brn","s26","s12", "s27", "s35", "s17", "s29", "s23", "s10","s3", "s15","s1", "s9", "s13", "s18", "s33", "s5", "s31", "s6", "s20","s11", "s22", "s14", "s30")

```


```{r}
str(count_exo)
str(quality_exo)
```


### Plots

```{r}
ggplot(data=quality_exo, aes(x=rownames(quality_exo), y=readsRaw)) +
    geom_bar(stat="identity", fill="steelblue")+
    geom_text(aes(label=rownames(quality_exo)), vjust=1.6, color="white", size=3.5)+
    theme_minimal()
```

```{r}
boxplot(count_exo, ylab="Log2-CPM",las=2, xlab="", cex.axis=0.8, main="Boxplots of logCPMs (unnormalised)", ylim=c(1,3))
```



```{r}
plotMDS(count_exo, main="MDS", cex=0.7)
```


```{r}
datos<-DESeqDataSetFromMatrix(countData = round(count_exo), colData= metadata_exo, design = ~ 1)
```

```{r}
PCAdata <- prcomp(t(assay(datos)))
fviz_pca_ind(PCAdata, repel = TRUE)
```


```{r}
clusters2 <- hclust(dist( t( assay(datos) ) ), method ="ward.D")
plot(clusters2)
```


```{r}

sampleDists <- dist( t( assay(datos) ) )
sampleDistMatrix <- as.matrix( sampleDists)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists, main = "Sample Distance Matrix ")

```


# Parámetros de calidad

```{r}

# Añado shortnames

values <- c("A","B","C","D","E","F","G", "H")
tipos_exo$batch<-as.factor(tipos_exo$batch)
tipos_exo$batch_shortname <- values[tipos_exo$batch]
tipos_exo$X<-ifelse(tipos_exo$X=="readsPerc","Reads%")

# Reads

tipos_exo <- tipos_exo |> 
    mutate(sample1 = reorder(sample, -ifelse(!X %in% "Reads%", 0, value), FUN = sum))

p1 <- ggplot(tipos_exo,aes(x = sample1, y = value, fill = factor(X, levels=c("Reads%")), width=1.05)) +
    geom_bar( stat = "identity", position = position_stack()) +
    scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
    labs(x = NULL, y= "% reads" , title="Reads % QC", fill="Quality Control") +
    theme(axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
    theme(
        panel.background = element_rect(fill='transparent'),
        plot.background = element_rect(fill='transparent', color=NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.background = element_rect(fill='transparent'),
        legend.box.background = element_rect(fill='transparent')
    )

tipos_exo1 <- tipos_exo |>
    distinct(sample, sample1, batch_shortname)
p_axis <- ggplot(tipos_exo1, aes(x = sample1, y = factor(1), fill = batch_shortname)) +
    geom_tile(width = 1) +
    theme_void() +
    theme(axis.title.x = element_text(), legend.position=c(1.09,2.6)) +
    labs(x="Batch Annotation", fill="Batch") 

p1_q<-p1 / p_axis + plot_layout(heights = c(8,1))  + scale_fill_igv()



# Cerebro

p_reads_brain<-ggplot(brainq,aes(x = sample, y = value1, fill=variable1)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
labs(x = NULL, y= "% reads" , title="Brain Reads QC") +
theme(axis.text.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_reads_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text())  +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p3_qb<-p_reads_brain / p_axis_reads_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()



plot_grid(p1_q,p3_qb, rel_widths = c(2, 1))



```


```{r}

# Cortos


short$batch<-as.factor(short$batch)
short$batch_shortname <- values[short$batch]
short$X<-ifelse(short$X=="shortReadsPerc","Short reads %")


p_short<-ggplot(short,aes(x = reorder(sample, -value), y = value, fill = factor(X, levels=c("Short reads %")), width=1.05)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 30, by = 5)) +
labs(x = NULL, y= "% short reads" , title="Short Reads QC", fill="Quality Control") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
)
p_axis_short <- ggplot(short, aes(x = reorder(sample, -value), y = factor(1), fill = batch_shortname)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text(), legend.position=c(1.09,2.6)) +
labs(x="Batch Annotation", fill="Batch")
p3q<-p_short / p_axis_short + plot_layout(heights = c(8, 1))  + scale_fill_igv()


# Cerebro

p_short_brain<-ggplot(brainq,aes(x = sample, y = value2, fill = variable2)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 1)) +
labs(x = NULL, y= "% reads" , title="Brain short reads QC", fill="QC") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_short_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text()) +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p4_qb<-p_short_brain / p_axis_short_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()


plot_grid(p3q,p4_qb, rel_widths = c(2, 1))
```



```{r}

ushort$batch<-as.factor(ushort$batch)
ushort$batch_shortname <- values[ushort$batch]
ushort$X<-ifelse(ushort$X=="ultraShortReadsPerc","Ultra short %")

# Ultra cortos

p_ushort<-ggplot(ushort,aes(x = reorder(sample, -value), y = value, fill= factor(X, levels=c("Ultra short %")), width=1.05)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 80, by = 10)) +
labs(x = NULL, y= "% ultra short reads" , title="Ultra Short Reads QC", fill="Quality Control") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
)
p_axis_ushort <- ggplot(ushort, aes(x = reorder(sample, -value), y = factor(1), fill = batch_shortname)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text(), legend.position=c(1.09,2.6)) +
labs(x="Batch Annotation", fill="Batch")
p5_q<-p_ushort / p_axis_ushort + plot_layout(heights = c(8, 1))  + scale_fill_igv()



# Cerebro

p_ushort_brain<-ggplot(brainq,aes(x = sample, y = value3, fill = "none")) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 5)) +
labs(x = NULL, y= "% reads" , title="Brain Ultra Short Reads QC") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_ushort_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text())  +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p5_qb<-p_ushort_brain / p_axis_ushort_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()



plot_grid(p5_q,p5_qb, rel_widths = c(2, 1))

```



```{r}

ref.genome$batch<-as.factor(ref.genome$batch)
ref.genome$batch_shortname <- values[ref.genome$batch]


# Genoma de referencia


p_ref.genome<-ggplot(ref.genome,aes(x = reorder(sample, -value), y = value, fill= factor(variable, levels=c("% ref.genome")), width=1.05)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
labs(x = NULL, y= "% reads" , title="Reference genome % Reads QC", fill="Quality Control") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
)
p_axis_ref.genome<- ggplot(ref.genome, aes(x = reorder(sample, -value), y = factor(1), fill = batch_shortname)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text(), legend.position=c(1.12,2.6)) +
labs(x="Batch Annotation", fill="Batch")
p6_q<-p_ref.genome / p_axis_ref.genome + plot_layout(heights = c(8, 1))  + scale_fill_igv()


# Cerebro

p_ref.genome_brain<-ggplot(brainq,aes(x = sample, y = value4, fill = "none")) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
labs(x = NULL, y= "% reads" , title="Brain Ref Genome QC") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_ref.genome_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text())  +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p6_qb<-p_ref.genome_brain / p_axis_ref.genome_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()

plot_grid(p6_q,p6_qb, rel_widths = c(2, 1))

```



```{r}
unmapped$batch<-as.factor(unmapped$batch)
unmapped$batch_shortname <- values[unmapped$batch]
unmapped$variable<-ifelse(unmapped$variable=="unmapped","Unmapped %")
# Unmapped

p_unmapped<-ggplot(unmapped,aes(x = reorder(sample, -value), y = value, fill = variable, width=1.05)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
labs(x = NULL, y= "% reads" , title="Unmapped % Reads QC", fill="Quality Control") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
)
p_axis_unmapped<- ggplot(unmapped, aes(x = reorder(sample, -value), y = factor(1), fill = batch_shortname)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text(), legend.position=c(1.12,2.6)) +
labs(x="Batch Annotation", fill="Batch")
p7_q<-p_unmapped / p_axis_unmapped + plot_layout(heights = c(8, 1))  + scale_fill_igv()


p_unmapped_brain<-ggplot(brainq,aes(x = sample, y = value5, fill = "none")) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
labs(x = NULL, y= "% reads" , title="Unmapped Brain QC") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_unmapped_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text())  +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p7_qb<-p_unmapped_brain / p_axis_unmapped_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()


plot_grid(p7_q,p7_qb, rel_widths = c(2, 1))

```


```{r}
bacteria$batch<-as.factor(bacteria$batch)
bacteria$batch_shortname <- values[bacteria$batch]
bacteria$variable<-ifelse(bacteria$variable=="bacteria","Bacteria %")

# Bacteria

p_bacteria<-ggplot(bacteria,aes(x = reorder(sample, -value), y = value, fill = variable, width=1.05)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 10)) +
labs(x = NULL, y= "% reads" , title="Bacteria % Reads QC", fill="Quality Control") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
)
p_axis_bacteria<- ggplot(bacteria, aes(x = reorder(sample, -value), y = factor(1), fill = batch_shortname)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text(), legend.position=c(1.12,2.6)) +
labs(x="Batch Annotation", fill="Batch")
p8_q<-p_bacteria / p_axis_bacteria + plot_layout(heights = c(8, 1))  + scale_fill_igv()


p_bacteria_brain<-ggplot(brainq,aes(x = sample, y = value6, fill = "none")) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 1)) +
labs(x = NULL, y= "% reads" , title="Bacteria Brain QC") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_bacteria_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text())  +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p8_qb<-p_bacteria_brain / p_axis_bacteria_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()


plot_grid(p8_q,p8_qb, rel_widths = c(2, 1))


```



```{r}
# Virus

virus$batch<-as.factor(virus$batch)
virus$batch_shortname <- values[virus$batch]
virus$variable<-ifelse(virus$variable=="virus","Virus %")

p_virus<-ggplot(virus,aes(x = reorder(sample, -value), y = value, fill = variable, width=1.05)) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 10, by = 1)) +
labs(x = NULL, y= "% reads" , title="Virus % Reads QC", fill="Quality Control") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
)
p_axis_virus<- ggplot(virus, aes(x = reorder(sample, -value), y = factor(1), fill = batch_shortname)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text(), legend.position=c(1.12,2.6)) +
labs(x="Batch Annotation", fill="Batch Annotation")
p9_q<-p_virus / p_axis_virus + plot_layout(heights = c(8, 1))  + scale_fill_igv()



p_virus_brain<-ggplot(brainq,aes(x = sample, y = value7, fill = "none")) +
geom_bar( stat = "identity") +
scale_y_continuous(expand = c(0, 0), breaks = seq(0, 100, by = 0.1)) +
labs(x = NULL, y= "% reads" , title="Virus Brain QC") +
theme(axis.text.x = element_blank(),
axis.ticks.x = element_blank(),
axis.ticks.length.x = unit(0, "pt")) + scale_fill_jco()+
theme(
panel.background = element_rect(fill='transparent'),
plot.background = element_rect(fill='transparent', color=NA),
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
legend.background = element_rect(fill='transparent'),
legend.box.background = element_rect(fill='transparent')
) +
theme(legend.position="none")
p_axis_virus_brain <- ggplot(brainq, aes(x =sample, y = factor(1), fill = batch)) +
geom_tile(width = 1) +
theme_void() +
theme(axis.title.x = element_text())  +
labs(x="Batch Annotation", fill="Batch Annotation") +
theme(legend.position="none")
p9_qb<-p_virus_brain / p_axis_virus_brain + plot_layout(heights = c(8, 1))  + scale_fill_igv()

plot_grid(p9_q,p9_qb, rel_widths = c(2, 1))
```


## Construccion de la matriz de expresion

```{r}

# Pasamos este script pot cada batch para montar su matriz de expresión, luego lo usamos para montar otra a partir de ellas.

setwd("/home/david_caceres/Exosomas/Exosomas/Expresion/Expresion_180322-190603/")
filenames <- list.files(pattern="*.tsv") # Leo los archivos de una carpeta
all_files <- lapply(filenames,function(x) { # Cargo los archivos y añado espacios
read.table(file = x,
sep = '\t',
header = TRUE)
})
list3<- lapply(all_files, "[", c(1,3)) # Extraigo las 2 columnas que necesito
matrixA<-rbindlist(list3,fill=TRUE) # Uno todos los dataframes en uno
matrixA %>% distinct() # Compruebo si hay duplicados en la columna de miRnas
list4 <- lapply(list3, function(x) x[!duplicated(x$name),])
matrixA<-rbindlist(list4,fill=TRUE)
write.table(matrixA, file = "matrixA.tsv", append = FALSE, quote = TRUE, sep = "\t ")
```


## Análisis


```{r}

# Directorios y cargo archivos

setwd("/home/david_caceres/Exosomas/Exosomas2/Expresion/Matrices de Expresion/")

filenames <- list.files(pattern="*.tsv")

matriz<-read.delim(file="/home/david_caceres/Exosomas/Exosomas2/Expresion/Matrices de Expresion/matrixXA.tsv", row.names=1)
matriz[is.na(matriz)] = 0

names(matriz)=str_sub(names(matriz),2) #Quitamos las X
names(matriz) <- gsub(x = names(matriz), pattern = "\\.", replacement = "-") # Cambio los puntos de las muestras de cerebro por guiones



meta<-read.table(file="/home/david_caceres/Exosomas/Exosomas2/metadata.tsv", header = TRUE, sep = "\t")
meta = meta[-180,]

cross<-read.csv(file="/home/david_caceres/Exosomas/Exosomas2/CrossSectional.minInfo.csv", header = TRUE, sep = ",")


# Preparemos los metadatos

meta2 <- strsplit(as.character(meta$sample),'_EXO_')


meta3<-do.call(rbind, meta2)

meta4<-cbind(meta, meta3)

colnames(meta4)= c("sample", "batch","batch_shortname", "OMICID", "smp" )

head(meta4)


# Unimos todos los metadatos en un archivo

cross2<-merge(cross, meta4, by="OMICID")

cross2[, 'batch_shortname'] <- as.factor(cross2[, 'batch_shortname'])

cross2$sample_shortname<-paste(cross2$batch_shortname, cross2$smp)

cross2$Diagnosis[is.na(cross2$Diagnosis)] = "Control"

cross2<-cross2[,-2]

Reads<-data.frame(tipos_exo$sample,tipos_exo$value)
colnames(Reads)<-c("sample","Reads")
cross2<-merge(cross2, Reads, by="sample")

Short_reads<-data.frame(short$sample,short$value)
colnames(Short_reads)<-c("sample","Short_reads")
cross2<-merge(cross2, Short_reads, by="sample")

Ultra_short_reads<-data.frame(ushort$sample,ushort$value)
colnames(Ultra_short_reads)<-c("sample","Ultra_short_reads")
cross2<-merge(cross2, Ultra_short_reads, by="sample")

Bacteria<-data.frame(bacteria$sample,bacteria$value)
colnames(Bacteria)<-c("sample","Bacteria")
cross2<-merge(cross2, Bacteria, by="sample")

Virus<-data.frame(virus$sample,virus$value)
colnames(Virus)<-c("sample","Virus")
cross2<-merge(cross2, Virus, by="sample")


# Quito las muestras de cerebro

matriz2<-matriz %>% dplyr::select(-contains("Brain"))

# Damos el mismo orden de columnas a matriz y metadatos

setcolorder(matriz2,cross2$sample)

# Compruebo que sean iguales

all.equal(colnames(matriz2), cross2$sample)


```

# Análisis 

```{r}


# Filtramos por CPM y eliminamos conteos bajos

counts.CPM <- cpm(matriz2)
thresh <- counts.CPM > 0.5
head(thresh)

# Me quedo con los que pasan el umbral
keep <- rowSums(thresh) >= 20
counts.keep <- matriz2[keep,]

# # Monto la DGEList
# DGEList(counts.keep, group = cross2$batch_shortname)
# dgeObj <- DGEList(counts.keep)
# names(dgeObj)
# logcounts <- cpm(dgeObj,log=TRUE)
# dgeObj_norm <- calcNormFactors(dgeObj)
# logcounts_norm <- cpm(dgeObj_norm,log=TRUE)
# sampleDists <- dist(t(logcounts_norm))
# cross2$batch_shortname <- factor (cross2$batch_shortname)
# col.status <- c("blue","red","dark green","yellow","lightblue4","orange3", "lightskyblue", "violetred4")[cross2$batch_shortname]
# data.frame(cross2$batch_shortname,col.status)
# plotMDS(logcounts_norm,col=col.status, main="Batch", cex=0.9, pch=16)
# legend("right", inset=c(-0.092,0),
# fill=c("blue","red","dark green","yellow","lightblue4","orange3", "lightskyblue", "violetred4"),
# legend=levels(cross2$batch_shortname), title="Batch")


```



# MDS GGplot VST Batch

```{r}
# Filtramos por CPM y eliminamos conteos bajos

counts.CPM <- cpm(matriz2)
thresh <- counts.CPM > 0.5

# Me quedo con los que pasan el umbral
keep <- rowSums(thresh) >= 20
counts.keep <- matriz2[keep,]

# Matriz de diseño

design  <-  model.matrix(~0+cross2$Diagnosis)

# Objeto de DESseq

dds <- DESeqDataSetFromMatrix(counts.keep,
colData = cross2,
design = design)

dim(dds)


```



```{r}
# Multi dimensional scaling

vsd <- varianceStabilizingTransformation(dds,blind=TRUE)

mds <- cmdscale(dist(t(assay(vsd))))
cross2.mds <- merge(x = cross2,y = mds,by.x='sample',by.y='row.names')

colnames(cross2.mds)<-c("sample","OMICID","Age","Sex","Race","Diagnosis","Center","PatientID","batch","Batch" ,"smp","sample_shortname","Reads","Short_reads","Ultra_short_reads","Bacteria","Virus","V1","V2")


ggplot(cross2.mds, aes(x = V1, y = V2, color = Batch)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Batch") + stat_ellipse() + theme_bw() + scale_color_igv()

ggplot(cross2.mds, aes(x = V1, y = V2, color = Sex)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Sex") + stat_ellipse() + theme_bw() + scale_color_igv()

ggplot(cross2.mds, aes(x = V1, y = V2, color = Diagnosis)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Diagnosis") + stat_ellipse() + theme_bw() + scale_color_igv()

ggplot(cross2.mds, aes(x = V1, y = V2, color = Center)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Center") + stat_ellipse() + theme_bw() + scale_color_igv()

ggplot(cross2.mds, aes(x = V1, y = V2, color = Age)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Age") + theme_bw() + scale_color_gradient(low="white", high="red")

ggplot(cross2.mds, aes(x = V1, y = V2, color = Reads)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Reads") + theme_bw() + scale_color_gradient(low="white", high="red")

ggplot(cross2.mds, aes(x = V1, y = V2, color = Short_reads)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Short reads") + theme_bw() + scale_color_gradient(low="white", high="red")

ggplot(cross2.mds, aes(x = V1, y = V2, color = Ultra_short_reads)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Ultra short reads") + theme_bw() + scale_color_gradient(low="white", high="red")

ggplot(cross2.mds, aes(x = V1, y = V2, color = Bacteria)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Bacteria") + theme_bw() + scale_color_gradient(low="white", high="dark blue")

ggplot(cross2.mds, aes(x = V1, y = V2, color = Virus)) +
    geom_point(size = 3) + coord_fixed() + ggtitle("MDS Virus") + theme_bw() + scale_color_gradient(low="white", high="dark blue")

```

# Paquete swamp para delimitar de donde viene la variación. Empirical bayes. Combat, combinación de batches

```{r}
cross3<-data.frame(cross2$Age,cross2$Gender,cross2$Diagnosis,cross2$batch_shortname, cross2$Reads,cross2$Short_reads,cross2$Ultra_short_reads, cross2$Bacteria, cross2$Virus)
rownames(cross3)<-cross2$sample
colnames(cross3)<-c("Age","Gender","Diagnosis","Batch","Reads","Short Reads", "Ultra short reads", "Bacteria", "Virus")
all.equal(colnames(vsd), rownames(cross3))

cross3$Gender<-as.factor(cross3$Gender)
cross3$Age<-as.numeric(cross3$Age)
cross3$Diagnosis<-as.factor(cross3$Diagnosis)


#com1<-combat(logcounts_norm, cross3$Batch, batchcolumn=1)


pr_out <- prince(assay(vsd),cross3,top=20,center = TRUE)
prince.plot(pr_out,note = TRUE,Rsquared = TRUE)
# No puedo usar kill.pc porque el género es una   asociación biológica.



```

